branch-defaults:
  master:
    environment: coindcx-candles-api-live
    group_suffix: null
global:
  application_name: coindcx-candles-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
