default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: ccapi
  password: ccapi
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coindcx_candles_api_development

test:
  <<: *default
  database: coindcx_candles_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>